### ISSUE TITLE
Single chars are highlighted under comments

### ISSUE THREAD

**Issue by lpan** [hkmix/vim-george#2]
![image](https://user-images.githubusercontent.com/12106903/30837144-e07e98d8-a230-11e7-8794-da8671bd2838.png)

neovim v0.2.0 on Fedora 26

cc @aidenbenner

**Comment by hkmix** [comment]
Looking into this.

**Comment by hkmix** [comment]
Looks like the original goal was to highlight propositions in the form of any character from a to z, but the regex was bad. I've fixed this in 5a1ce90. Feel free to reopen the issue if you have further issues, thanks!

EDIT: Latest master should have the fixed version. If you feel like comments shouldn't be highlighted at all, let me know and I can turn this into a configurable option.

**Comment by lpan** [comment]
thanks so much!
